### ISSUE TITLE
Enable students to view the grades

### ISSUE THREAD

**Issue by jmahal1** [jmahal1/githubflow#1]
**User Story**:

Students wish to know their grades immediately as soon as homework, quizzes, and tests are scored and inputted by the instructor. This allows them to know where they stand in the course at all times, and let's them figure out what final grade they can get in the course based on points accrued and remaining total points. Not having to ask the teacher for their overall grade or individual scores, but to be able to see it at any time at their own convenience as well as play around with possible scores empowers them to have vital academic information at their fingertips and map out their planning for the course(s). 

*persona: student who wants to see scores, overall grades 
*feature: posted scores, grades in given course(s)
*business value: student's can know whenever they want what their grade is when grades are put in, don't have to wait to ask teacher in person; can also play around with hypothetical scores 

**Task List**:
- [x] HTML/CSS display for rows and columns naming all course(s) assignments, along with scores and grades
- [ ] Calculation for individual scores and overall grade; requisite methods and functions
- [x] Displaying the corresponding letter grades from percentages (ranges based on course syllabus)

**Acceptance Criteria**:
1. only for students enrolled in given course(s) 
2. only the given course(s) for this current semester

**Acceptance Tests**:
1. student should be able to see all up to date individual scores from teacher
2. student should be able to see overall grade based on individual scores inputted
3. student should only be able to see his/her own grades, no other student's grades
4. students can see anonymous class data regarding high score, low score, mean score for each graded item
5. students should be able to calculate possible grade based on course(s) possible points
